// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:85369928-d677-4a5b-9ad3-10765ea1f0c8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_N1p7nmpFb",
    "aws_user_pools_web_client_id": "4kcl3i8nce2v0mn5i35rhg6k6k",
    "oauth": {},
    "aws_content_delivery_bucket": "todolist-tdl",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://localhost:4201", //"http://todolist-tdl.s3-website.eu-central-1.amazonaws.com"
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "todolists-tdl",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
